name: StopBlock
main: Mohi/StopBlock/StopBlock
author: "Mohi(물외한인)"
version: "1.0"
api:
- 1.12.0
- 1.13.0
- 2.0.0

permissions:
 stopBlock.command.allow:
  descript: "StopBlock command permmision"
  default: OP